name: CUPS Print Server
version: "1.1.1"
slug: cups
description: The CUPS (Common UNIX Printing System) print server package with drivers included and Avahi
url: https://github.com/peternicholls/ha-cups-addon
arch:
  - aarch64
  - armhf
  - armv7
  - amd64
  - i386
usb: true
init: false
homeassistant_api: true
host_network: true
panel_icon: mdi:printer
icon: icon.png
logo: icon.png
ports:
  631/tcp: 631
  631/udp: 631
ports_description:
  631/tcp: Used by other devices on the local network to post print jobs to this server (TCP)
  631/udp: Used by other devices on the local network to post print jobs to this server (UDP)
ingress: true
ingress_port: 8099
map:
  - config:rw
  - ssl
options:
  admin_user: print
  admin_password: print
  cups_log_level: warn
  default_paper_size: A4
schema:
  admin_user: str
  admin_password: password
  cups_log_level: list(warn|info|debug)
  default_paper_size: list(A4|Letter)
